name: "render"

on:
  workflow_call:

jobs:
  cv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version-file: .python-version
      - name: Install RenderCV
        run: pip install "rendercv[full]==2.8"
      - name: Build artifact
        run: >
          rendercv render src/cv.yaml
          --dont-generate-markdown --dont-generate-html --dont-generate-png
          --typst-path ./out/cv.typ
          --pdf-path ./out/diogo_simoes_cv.pdf
      - name: Upload artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: cv
          path: ./out/diogo_simoes_cv.pdf
